### ISSUE TITLE
"SyntaxError: Expected end of stream at char 4"

### ISSUE THREAD

**Issue by borgreu** [samsmu/JIRA2PM#45] opened 2018-05-11 16:30 UTC
Getting this error when getting the result.

Connection to Jira is fine. 
Same error no matter what JQL i use.

**Comment by BlackCatter** [comment] 2018-05-14 18:28
Hi, @borgreu ! Thank you for submitting this issue :D

Problem was with parsing information about custom fields. For now I have added fallback scenario, where if there was such error, custom fields are not used. This changes should be published soonish to the Google store.

But I can't reproduce this issue with my Jira server which prevents me from finding the real root of this error. 
If it is ok with you, can you provide information about
1) How long have you been using Jira2pm?
2) Have you ever used button "Update Custom FIelds"?
3) Does your Jira setup include any custom fields?

**Comment by borgreu** [comment] 2018-05-14 18:36
Hi @BlackCatter 
Thank you for the response!
1. About 2 months, but encountering this issue approximately these last 2 or 3 weeks
2. Yes
3. Yes, many

**Comment by borgreu** [comment] 2018-05-17 07:28
Hi @BlackCatter 
Thank you for the fix. The add-on is now working.
However, like you said, Custom Fields are not retrieved. When clicking **Reload Custom Fields**, the following error is returned: _ScriptError: Argument too large: value_

**Comment by BlackCatter** [comment] 2018-05-17 07:33
@borgreu Glad to hear!

I will get better look at logs to get whats wrong with custom fields at the weekends.

**Comment by BlackCatter** [comment] 2018-06-06 06:46
@borgreu Hi! Issue with custom fields should be fixed. Can you check and confirm it?

**Comment by borgreu** [comment] 2018-06-28 09:15
@BlackCatter  - Not sure if it is related, but I'm getting this error when loading Custom Fields:
"ScriptError: Argument too large: value"
Is there a limit on the number of custom fields retrieved?

**Closed** 2023-03-23 02:01 UTC
